### PR TITLE
Remove automatic import of Google Fonts for #309

### PR DESCRIPTION
**Pull request by codymullins**

### CODE REVIEW

**Comment by hperrin** [comment]
I'm wondering if it would be possible to have an option to import it for you...

**Comment by codymullins** [comment]
The only way I could imagine doing that is it we did it with JavaScript, in that case we’d need to wait to load the JS before rendering the CSS. 

Unless there’s another way I’m not thinking of, that is. Long as you don’t mind that I could make that change, not sure how much value it adds though?

**Comment by hperrin** [comment]
Hmm. Yeah, it doesn't really add much. We should include instructions on getting the Material Icon font from NPM too though, so you wouldn't have any remote requirements.

**Comment by codymullins** [comment]
Fair enough, that's a good point. I've updated the readme with instructions for both NPM and directly referencing the CDN, I also updated the example page to use NPM.

**Pull request merged**
